/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MemoInfo } from './MemoInfo';

// 模拟记事本数据
export const MEMO_DATA: MemoInfo[] = [
  new MemoInfo('1646121972443', 'One step', 'Just now', 'app.media.ic_public_app5', 'For analyzing the data gathered in the previous experiment.'),
  new MemoInfo('1646121972444', 'Love is love', '5 min ago', '', 'Start whenever you want.'),
  new MemoInfo('1646121972445', 'To solve a problem', 'Yesterday', 'app.media.drink_coffee', 'To solve a problem. First, you need to gain empty mind.'),
  new MemoInfo('1646121972446', 'Lunches', '02.18.2024', 'app.media.cook_picture', 'Sweet and sour ribs potato shreds'),
  new MemoInfo('1646121972447', 'Computer Lessons', '02.22.2024', '', 'Learning HarmonyOS'),
  new MemoInfo('1646121972448', 'Morning Exercise', '02.20.2024', 'app.media.ic_public_app12', 'Long run 3 km'),
  new MemoInfo('1646121972449', 'Breakfast', '02.17.2024', 'app.media.dinner_food', 'Milk and bread'),
  new MemoInfo('1646121972450', 'Go to work', '02.15.2024', 'app.media.ic_public_game1', 'Take the 11th bus')
];