/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class SideBarAnimationViewConstants {
  static readonly SIDEBAR_ANIMATION_DURATION: number = 500;
  static readonly SIDEBAR_WIDTH: number = 200;
  static readonly GROUP_NAME_FONT_WEIGHT: number = 16;
  static readonly MEMBER_COUNT: number = 10;
  static readonly SIDEBAR_OPACITY_SHOW: number = 1;
  static readonly SIDEBAR_OPACITY_HIDDEN: number = 0;
  static readonly SIDEBAR_IS_SHOW_BUTTON: boolean = false;
  static readonly SIDEBAR_IS_BUTTON_AUTORESIZE: boolean = true;
  static readonly SIDEBAR_IS_AUTO_HIDE: boolean = false;
}