/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const CONFIGURATION: Record<string, number> = {
  'TABBAR_TEXT_CURRENTINDEX_FONTWEIGHT': 500,
  'TABBAR_TEXT_FONTWEIGHT': 400,
  'BOTTOM_TABS_ANIMATIONDURATION': 400,
  'BOTTOM_TABS_TABBUILDER_DIVIDER_STROKEWIDTH': 2,
  'TABS_TABBAR_INDEX0': 0,
  'TABS_TABBAR_INDEX1': 1,
  'TABS_TABBAR_INDEX2': 2,
  'TABS_TABBAR_INDEX3': 3,
  'TABS_TABBAR_INDEX4': 4,
  'ZINDEX1': 1,
  'ZINDEX2': 2,
  'PANGESTURE_FINGERS': 1,
  'PANGESTURE_DISTANCE': 1,
  'INIT_VALUE': 0,
  'IMAGE_FULL_SIZE': 320,
  'LEFT_IMAGE_RIGHT_LIMIT_SIZE': 290,
  'RIGHT_IMAGE_RIGHT_LIMIT_SIZE': 30,
  'LEFT_IMAGE_LEFT_LIMIT_SIZE': 30,
  'RIGHT_IMAGE_LEFT_LIMIT_SIZE': 290,
  'DESIGNCATTLEVIEW_TEXT_ASPECTRATIO': 1,
  'END_VALUE': 4,
  'WATERFLOW_TEXT_MAXLINES': 2,
  'WATERFLOW_TABBAR_LINEARGRADIENT_ANGLE': 180,
  'TABBAR_LINEARGRADIENT_COLOR_ZERO': 0,
  'TABBAR_LINEARGRADIENT_COLOR_ONE': 1,
  'TABBAR_TEXT_OPACITY_SELECTED': 1,
  'TABBAR_TEXT_OPACITY': 0.8,
  'TABBAR_TEXT_FONT_WEIGHT_SELECTED': 600,
  'TABBAR_TEXT_FONT_WEIGHT': 400,
  'TABBAR_TEXT_BORDER_WIDTH': 0,
  'TABBAR_TEXT_BORDER_WIDTH_BOTTOM': 2,
  'WATERFLOW_CACHEDCOUNT': 8,
  'DRAGTOSWITCHPICTURES_DURATION': 300,
}
