/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const DATA_CONFIG: Record<string, number> = {
  'NUMBER_LEN': 7, // 数字个数
  'DURATION_TIME': 200, // 动画时长
  'MILLENNIAL_LEN': 3 // 千分位长度
}

export const STYLE_CONFIG: Record<string, number> = {
  'ITEM_GUTTER': 12, // 元素间距
  'ITEM_HEIGHT': 26, // 数字元素高度
  'TEXT_MARGIN': 2, // 文本间距
  'PADDING_TOP': 32  // 顶部边距
}