/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ImageCropConstants {
  static readonly THREE_FOUR: number = 4 / 3;                 // 裁剪比例
  static readonly NINE_SIXTH: number = 16 / 9;                // 裁剪比例
  static readonly ONE_ONE: number = 1;                        // 裁剪比例
  static readonly RAWFILE_PICPATH: string = "depthCopy.png";  // rawfile中的图片名
}