/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License"),
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expreIndexss or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const CONFIGURATION: Record<string, number> = {
  'TABBAR_TEXT_CURRENTINDEX_FONTWEIGHT': 500,
  'PAGEFLIPTWO': 2,
  'PAGEFLIPZERO': 0,
  'PAGEFLIPONE': 1,
  'PAGEFLIPTHREE': 3,
  'PAGEFLIPFOUR': 4,
  'PAGEFLIPFIVE': 5,
  'PAGEFLIPTWELVE': 12,
  'PAGEFLIPTHIRTEEN': 13,
  'FLIPPAGEZINDEX': 2,
  'PAGEFLIPBOTTOMBLANKBEIGHT': 0.3,
  'PAGEFLIPBORDERWIDTH': 2,
  'PAGEFLIPTOASTDURATION': 300,
  'WINDOWWIDTH': 600,
  'PAGEFLIPPAGECOUNT': 1,
  'PAGEFLIPPAGESTART': 1,
  'PAGEFLIPPAGEEND': 14,
  'PAGEFLIPRIGHTFLIPOFFSETX': 10,
  'PAGEFLIPLEFTFLIPOFFSETX': -10,
  'PAGEFLIPCACHECOUNT': 3,
  'LETTERSPACING': 3,
}

export const STRINGCONFIGURATION: Record<string, string> = {
  'PAGEFLIPRESOURCE': 'app.string.pageflip_content',
  'PAGEFLIPVIEWLIST': 'flippage_view_list',
  'PAGEFLIPFREE': 'flippage_free',
  'PAGEFLIPDISCOVER': 'flippage_discover',
  'PAGEFLIPBRIGHTNESS': 'flippage_brightness',
  'PAGEFLIPSETTINGS': 'flippage_settings',
  'LEFTRIGHTFLIPPAGENAME': '左右翻页',
  'UPDOWNFLIPPAGENAME': '上下翻页',
  'COVERFLIPPAGENAME': '覆盖翻页',
  'FLIPPAGECLOUDUPLOAD': 'app.media.flippage_cloud_upload',
  'FLIPPAGECONTACTS': 'app.media.flippage_contacts',
  'FLIPPAGESHAREFILLED': 'app.media.flippage_share_filled',
  'FLIPPAGEMOREFILLED': 'app.media.flippage_more_filled',
}