/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 默认图片url
export const DEFAULT_IMG_URL: string = 'https://gitee.com/harmonyos-cases/cases/raw/master/CommonAppDevelopment/feature/imageenableanalyzer/src/main/resources/base/media/cat2.JPG';

// 默认图片Referer
export const DEFAULT_REFER: string = 'https://gitee.com/';

// column间隔
export const IMAGE_THEFT_COLUMN_SPACE: number = 10;

// 图片组件宽度
export const IMAGE_THEFT_IMAGEKNIFE_COMPONENT_WIDTH: number = 360;

// 图片组件高度
export const IMAGE_THEFT_IMAGEKNIFE_COMPONENT_HEIGHT: number = 360;

// 按钮点击缩放
export const IMAGE_THEFT_BUTTON_CLICK_SCALE: number = 0.8;
