/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const CONFIGURATION: Record<string, number> = {
  'VIBRATION_TIME': 600,
  'ANIMATION_TIME': 100,
  'MARGIN_VERTICAL': 16,
  'FLEX_SHRINK': 1,
  'POPUP_POSITION_X': 8,
  'POPUP_POSITION_Y': 1,
  'MARK_POSITION_X': 4,
  'MARK_POSITION_Y': 9,
  'POSITION_ZERO': 0,
  'OPACITY_VALUE': 0.8,
  'PLAYBACK_COUNT': 2,
  'TRANSLATE_OFFSET_X': 5,
}
